<template>
  <q-page class="w-full px-5">
    <div class="row w-full">
      <q-input v-model="searchTerm" label="Type a movie title portion and press ENTER" lazy-rules :rules="searchRules" @keyup.enter="(luckyMethod = false), search()" class="w-full" />
    </div>
    <div class="row w-full">
      <q-btn depressed small color="primary" class="mx-auto mb-5 w-25" :disable="searchTerm.length < 3" @click="(luckyMethod = false), search()">Movie Search</q-btn>
      <q-btn depressed small color="primary" class="mx-auto mb-5 w-25" @click="(luckyMethod = true), search()">I'm lucky</q-btn>
    </div>
    <div class="row w-full" v-if="progressLoader === true">
      <q-circular-progress size="2rem" color="primary" class="mx-auto" indeterminate></q-circular-progress>
    </div>

    <section class="flex flex-wrap justify-center gap-3 mt-5">
      <q-card v-for="(movie, i) in moviesDetails" :key="i" class="relative max-w-[374px]">
        <img v-if="movie.Poster && movie.Poster != 'N/A'" :src="movie.Poster" class="object-cover h-[250px]" />
        <img v-else src="../assets/img/no-image.jpg" class="object-cover h-[250px]" />

        <q-btn
          icon="assignment"
          color="primary"
          class="white--text absolute right-3 top-[220px] right-[20px] opacity-75"
          :href="`https://www.imdb.com/title/${movie.imdbID}`"
          target="movie"
          fab
          small
        />

        <q-fab color="primary" icon="keyboard_arrow_down" direction="down" class="absolute top-[220px] right-[90px] opacity-90">
          <q-fab-action
            v-for="btn in agendaButtons"
            color="accent"
            @click="
              switch (btn.label) {
                case 'Delete':
                  delMovieAgenda(movie.imdbID);
                  break;
                default:
                  movieBtnAction(btn.label, movie.imdbID, movie.Title);
              }
            "
            :icon="btn.icon"
            :label="btn.label"
            :class="showHiddenBtns(movie.imdbID, btn.label)"
          />
        </q-fab>

        <q-card-section class="flex justify-around">
          <div class="text-h6 w-full">{{ movie.Title }}</div>

          <q-rating v-if="movie.imdbRating != 'N/A'" :model-value="Number(movie.imdbRating)" color="amber" icon-half="star_half" readonly max="10" size="1.4em" class="w-50"></q-rating>

          <div v-if="movie.imdbRating != 'N/A'" class="grey--text p-0 w-auto">
            {{ movie.imdbRating }}
          </div>

          <div class="grey--text p-0 w-auto">
            {{ movie.Year }}
          </div>

          <div class="grey--text pl-0 w-auto">
            {{ movie.Runtime }}
          </div>
        </q-card-section>

        <q-separator />

        <q-card-section>
          <div class="text-subtitle-1 w-100"><strong>Director:</strong> {{ movie.Director }}</div>

          <div class="text-subtitle-1 w-100"><strong>Actors:</strong> {{ movie.Actors }}</div>

          <div class="text-subtitle-1 w-100"><strong>Genre:</strong> {{ movie.Genre }}</div>
        </q-card-section>

        <q-separator />

        <q-card-section class="q-pt-none mt-3">
          {{ movie.Plot }}
          <!-- API limit 230 chars //-->
        </q-card-section>
      </q-card>
    </section>

    <div v-if="noMovie === true" class="text-center">
      <img src="../assets/img/not-found.gif" class="mt-3 w-[300px] mx-auto" />
    </div>

    <q-dialog class="movie-dialog" v-model="openAgendaDialog" persistent>
      <q-card class="min-h-[290px] min-w-[290px] max-w-[400px]" :class="{ 'flex justify-center content-center': movieAddedLoading === true }">
        <q-card-section v-if="movieAddedLoading === true">
          <q-spinner-pie color="primary" size="8em" />
        </q-card-section>

        <q-card-section v-else class="flex justify-center">
          <q-input filled v-model="countrySearch" label="Country" autofocus @blur="checkMovie" placeholder="Where'll you watch? (default: United States)" class="w-full mb-4 capitalize" />
          <q-date v-model="movieWatchDate" :options="movieWatchDateOpt" subtitle="" :title="dialogTitle" />
        </q-card-section>

        <q-card-actions v-if="movieAddedLoading === false" align="center" class="bg-white text-teal">
          <q-btn color="negative" @click="openAgendaDialog = false">Cancel</q-btn>
          <q-btn
            color="primary"
            @click="
              switch (dialogAction) {
                case 'Add':
                  getStreamingList();
                  break;
                case 'Edit':
                  editMovieAgenda();
              }
            "
            >Okay</q-btn
          >
        </q-card-actions>
      </q-card>
    </q-dialog>
  </q-page>
</template>

<script>
import { onMounted, ref, watch } from "vue";
import { useQuasar } from "quasar";
import axios from "axios";

export default {
  name: "Movies",
  setup() {
    const api_key = process.env.OMDBAPI_KEY;
    const streaming_key = process.env.STREAMING_KEY;
    const $q = ref(useQuasar());
    const api_streaming = axios.create({ baseURL: process.env.STREAMING_URL });

    // API Data
    const agendaButtons = ref([
      {
        icon: "event",
        label: "Add",
      },
      {
        icon: "edit_calendar",
        label: "Edit",
      },
      {
        icon: "event_busy",
        label: "Delete",
      },
    ]);
    const countriesList = ref([]);
    const countrySearch = ref("");
    const dialogAction = ref(String);
    const dialogTitle = ref(String);
    const flashURL = ref(URL);
    const luckyMethod = ref(Boolean);
    const movieAddedLoading = ref(false);
    const movieId = ref(String);
    const movieWatchDate = ref("");
    const moviesDetails = ref(Array);
    const moviesTitles = ref(Array);
    const openAgendaDialog = ref(false);
    const searchRules = ref([(value) => (value && value.length >= 3) || "Min 3 characters"]);
    const searchTerm = ref("");
    const selectedCountry = ref(String);
    const streamingList = ref([]);
    const watchMovies = ref([]);
    const noMovie = ref(false);
    const progressLoader = ref(false);

    // API Functions/Methods
    const today = () => {
      return new Date().toISOString().split("T")[0].replace(/-/g, "/");
    };

    const movieWatchDateOpt = (movieWatchDateOpt) => {
      return movieWatchDateOpt >= new Date().toISOString().split("T")[0].replace(/-/g, "/");
    };

    const getRandomWord = () => {
      const commonWords = [
        "ability",
        "I",
        "a",
        "able",
        "aboard",
        "about",
        "about",
        "above",
        "accept",
        "accident",
        "according",
        "account",
        "accurate",
        "acres",
        "across",
        "act",
        "action",
        "active",
        "activity",
        "actual",
        "actually",
        "add",
        "addition",
        "additional",
        "adjective",
        "adult",
        "adventure",
        "advice",
        "affect",
        "afraid",
        "after",
        "after",
        "afternoon",
        "again",
        "against",
        "age",
        "ago",
        "agree",
        "ahead",
        "aid",
        "air",
        "airplane",
        "alike",
        "alive",
        "all",
        "all",
        "allow",
        "almost",
        "alone",
        "along",
        "aloud",
        "alphabet",
        "already",
        "also",
        "also",
        "although",
        "am",
        "among",
        "amount",
        "an",
        "ancient",
        "and",
        "angle",
        "angry",
        "animal",
        "announced",
        "another",
        "answer",
        "ants",
        "any",
        "any",
        "anybody",
        "anyone",
        "anything",
        "anyway",
        "anywhere",
        "apart",
        "apartment",
        "appearance",
        "apple",
        "applied",
        "appropriate",
        "are",
        "area",
        "arm",
        "army",
        "around",
        "arrange",
        "arrangement",
        "arrive",
        "arrow",
        "art",
        "article",
        "as",
        "as",
        "aside",
        "ask",
        "asleep",
        "at",
        "at",
        "ate",
        "atmosphere",
        "atom",
        "atomic",
        "attached",
        "attack",
        "attempt",
        "attention",
        "audience",
        "author",
        "automobile",
        "available",
        "average",
        "avoid",
        "aware",
        "away",
        "baby",
        "back",
        "back",
        "bad",
        "badly",
        "bag",
        "balance",
        "ball",
        "balloon",
        "band",
        "bank",
        "bar",
        "bare",
        "bark",
        "barn",
        "base",
        "baseball",
        "basic",
        "basis",
        "basket",
        "bat",
        "battle",
        "be",
        "be",
        "bean",
        "bear",
        "beat",
        "beautiful",
        "beauty",
        "became",
        "because",
        "because",
        "become",
        "becoming",
        "bee",
        "been",
        "before",
        "began",
        "beginning",
        "begun",
        "behavior",
        "behind",
        "being",
        "believed",
        "bell",
        "belong",
        "below",
        "belt",
        "bend",
        "beneath",
        "bent",
        "beside",
        "best",
        "bet",
        "better",
        "between",
        "beyond",
        "bicycle",
        "bigger",
        "biggest",
        "bill",
        "birds",
        "birth",
        "birthday",
        "bit",
        "bite",
        "black",
        "blank",
        "blanket",
        "blew",
        "blind",
        "block",
        "blood",
        "blow",
        "blue",
        "board",
        "boat",
        "body",
        "bone",
        "book",
        "border",
        "born",
        "both",
        "bottle",
        "bottom",
        "bound",
        "bow",
        "bowl",
        "box",
        "boy",
        "brain",
        "branch",
        "brass",
        "brave",
        "bread",
        "break",
        "breakfast",
        "breath",
        "breathe",
        "breathing",
        "breeze",
        "brick",
        "bridge",
        "brief",
        "bright",
        "bring",
        "broad",
        "broke",
        "broken",
        "brother",
        "brought",
        "brown",
        "brush",
        "buffalo",
        "build",
        "building",
        "built",
        "buried",
        "burn",
        "burst",
        "bus",
        "bush",
        "business",
        "busy",
        "but",
        "but",
        "butter",
        "buy",
        "by",
        "by",
        "cabin",
        "cage",
        "cake",
        "call",
        "calm",
        "came",
        "camera",
        "camp",
        "can",
        "can",
        "canal",
        "cannot",
        "cap",
        "capital",
        "captain",
        "captured",
        "car",
        "carbon",
        "card",
        "care",
        "careful",
        "carefully",
        "carried",
        "carry",
        "case",
        "cast",
        "castle",
        "cat",
        "catch",
        "cattle",
        "caught",
        "cause",
        "cave",
        "cell",
        "cent",
        "center",
        "central",
        "century",
        "certain",
        "certainly",
        "chain",
        "chair",
        "chamber",
        "chance",
        "change",
        "changing",
        "chapter",
        "character",
        "characteristic",
        "charge",
        "chart",
        "check",
        "cheese",
        "chemical",
        "chest",
        "chicken",
        "chief",
        "child",
        "children",
        "choice",
        "choose",
        "chose",
        "chosen",
        "church",
        "circle",
        "circus",
        "citizen",
        "city",
        "class",
        "classroom",
        "claws",
        "clay",
        "clean",
        "clear",
        "clearly",
        "climate",
        "climb",
        "clock",
        "close",
        "closely",
        "closer",
        "cloth",
        "clothes",
        "clothing",
        "cloud",
        "club",
        "coach",
        "coal",
        "coast",
        "coat",
        "coffee",
        "cold",
        "collect",
        "college",
        "colony",
        "color",
        "column",
        "combination",
        "combine",
        "come",
        "come",
        "comfortable",
        "coming",
        "command",
        "common",
        "community",
        "company",
        "compare",
        "compass",
        "complete",
        "completely",
        "complex",
        "composed",
        "composition",
        "compound",
        "concerned",
        "condition",
        "congress",
        "connected",
        "consider",
        "consist",
        "consonant",
        "constantly",
        "construction",
        "contain",
        "continent",
        "continued",
        "contrast",
        "control",
        "conversation",
        "cook",
        "cookies",
        "cool",
        "copper",
        "copy",
        "corn",
        "corner",
        "correct",
        "correctly",
        "cost",
        "cotton",
        "could",
        "could",
        "count",
        "country",
        "couple",
        "courage",
        "course",
        "court",
        "cover",
        "cow",
        "cowboy",
        "crack",
        "cream",
        "create",
        "creature",
        "crew",
        "crop",
        "cross",
        "crowd",
        "cry",
        "cup",
        "curious",
        "current",
        "curve",
        "customs",
        "cut",
        "cutting",
        "daily",
        "damage",
        "dance",
        "danger",
        "dangerous",
        "dark",
        "darkness",
        "date",
        "daughter",
        "dawn",
        "day",
        "day",
        "dead",
        "deal",
        "dear",
        "death",
        "decide",
        "declared",
        "deep",
        "deeply",
        "deer",
        "definition",
        "degree",
        "depend",
        "depth",
        "describe",
        "desert",
        "design",
        "desk",
        "detail",
        "determine",
        "develop",
        "development",
        "diagram",
        "diameter",
        "did",
        "die",
        "differ",
        "difference",
        "different",
        "difficult",
        "difficulty",
        "dig",
        "dinner",
        "direct",
        "direction",
        "directly",
        "dirt",
        "dirty",
        "disappear",
        "discover",
        "discovery",
        "discuss",
        "discussion",
        "disease",
        "dish",
        "distance",
        "distant",
        "divide",
        "division",
        "do",
        "doctor",
        "does",
        "dog",
        "doing",
        "doll",
        "dollar",
        "done",
        "donkey",
        "door",
        "dot",
        "double",
        "doubt",
        "down",
        "dozen",
        "draw",
        "drawn",
        "dream",
        "dress",
        "drew",
        "dried",
        "drink",
        "drive",
        "driven",
        "driver",
        "driving",
        "drop",
        "dropped",
        "drove",
        "dry",
        "duck",
        "due",
        "dug",
        "dull",
        "during",
        "dust",
        "duty",
        "each",
        "eager",
        "ear",
        "earlier",
        "early",
        "earn",
        "earth",
        "easier",
        "easily",
        "east",
        "easy",
        "eat",
        "eaten",
        "edge",
        "education",
        "effect",
        "effort",
        "egg",
        "eight",
        "either",
        "electric",
        "electricity",
        "element",
        "elephant",
        "eleven",
        "else",
        "empty",
        "end",
        "enemy",
        "energy",
        "engine",
        "engineer",
        "enjoy",
        "enough",
        "enter",
        "entire",
        "entirely",
        "environment",
        "equal",
        "equally",
        "equator",
        "equipment",
        "escape",
        "especially",
        "essential",
        "establish",
        "even",
        "even",
        "evening",
        "event",
        "eventually",
        "ever",
        "every",
        "everybody",
        "everyone",
        "everything",
        "everywhere",
        "evidence",
        "exact",
        "exactly",
        "examine",
        "example",
        "excellent",
        "except",
        "exchange",
        "excited",
        "excitement",
        "exciting",
        "exclaimed",
        "exercise",
        "exist",
        "expect",
        "experience",
        "experiment",
        "explain",
        "explanation",
        "explore",
        "express",
        "expression",
        "extra",
        "eye",
        "face",
        "facing",
        "fact",
        "factor",
        "factory",
        "failed",
        "fair",
        "fairly",
        "fall",
        "fallen",
        "familiar",
        "family",
        "famous",
        "far",
        "farm",
        "farmer",
        "farther",
        "fast",
        "fastened",
        "faster",
        "fat",
        "father",
        "favorite",
        "fear",
        "feathers",
        "feature",
        "fed",
        "feed",
        "feel",
        "feet",
        "fell",
        "fellow",
        "felt",
        "fence",
        "few",
        "fewer",
        "field",
        "fierce",
        "fifteen",
        "fifth",
        "fifty",
        "fight",
        "fighting",
        "figure",
        "fill",
        "film",
        "final",
        "finally",
        "find",
        "fine",
        "finest",
        "finger",
        "finish",
        "fire",
        "fireplace",
        "firm",
        "first",
        "first",
        "fish",
        "five",
        "fix",
        "flag",
        "flame",
        "flat",
        "flew",
        "flies",
        "flight",
        "floating",
        "floor",
        "flow",
        "flower",
        "fly",
        "fog",
        "folks",
        "follow",
        "food",
        "foot",
        "football",
        "for",
        "for",
        "force",
        "foreign",
        "forest",
        "forget",
        "forgot",
        "forgotten",
        "form",
        "former",
        "fort",
        "forth",
        "forty",
        "forward",
        "fought",
        "found",
        "four",
        "fourth",
        "fox",
        "frame",
        "free",
        "freedom",
        "frequently",
        "fresh",
        "friend",
        "friendly",
        "frighten",
        "frog",
        "from",
        "from",
        "front",
        "frozen",
        "fruit",
        "fuel",
        "full",
        "fully",
        "fun",
        "function",
        "funny",
        "fur",
        "furniture",
        "further",
        "future",
        "gain",
        "game",
        "garage",
        "garden",
        "gas",
        "gasoline",
        "gate",
        "gather",
        "gave",
        "general",
        "generally",
        "gentle",
        "gently",
        "get",
        "get",
        "getting",
        "giant",
        "gift",
        "girl",
        "give",
        "give",
        "given",
        "giving",
        "glad",
        "glass",
        "globe",
        "go",
        "go",
        "goes",
        "gold",
        "golden",
        "gone",
        "good",
        "good",
        "goose",
        "got",
        "government",
        "grabbed",
        "grade",
        "gradually",
        "grain",
        "grandfather",
        "grandmother",
        "graph",
        "grass",
        "gravity",
        "gray",
        "great",
        "greater",
        "greatest",
        "greatly",
        "green",
        "grew",
        "ground",
        "group",
        "grow",
        "grown",
        "growth",
        "guard",
        "guess",
        "guide",
        "gulf",
        "gun",
        "habit",
        "had",
        "hair",
        "half",
        "halfway",
        "hall",
        "hand",
        "handle",
        "handsome",
        "hang",
        "happen",
        "happened",
        "happily",
        "happy",
        "harbor",
        "hard",
        "harder",
        "hardly",
        "has",
        "hat",
        "have",
        "having",
        "hay",
        "he",
        "headed",
        "heading",
        "health",
        "heard",
        "hearing",
        "heart",
        "heat",
        "heavy",
        "height",
        "held",
        "hello",
        "help",
        "helpful",
        "her",
        "her",
        "herd",
        "here",
        "herself",
        "hidden",
        "hide",
        "high",
        "higher",
        "highest",
        "highway",
        "hill",
        "him",
        "him",
        "himself",
        "his",
        "his",
        "history",
        "hit",
        "hold",
        "hole",
        "hollow",
        "home",
        "honor",
        "hope",
        "horn",
        "horse",
        "hospital",
        "hot",
        "hour",
        "house",
        "how",
        "how",
        "however",
        "huge",
        "human",
        "hundred",
        "hung",
        "hungry",
        "hunt",
        "hunter",
        "hurried",
        "hurry",
        "hurt",
        "husband",
        "ice",
        "idea",
        "identity",
        "if",
        "if",
        "ill",
        "image",
        "imagine",
        "immediately",
        "importance",
        "important",
        "impossible",
        "improve",
        "in",
        "in",
        "inch",
        "include",
        "including",
        "income",
        "increase",
        "indeed",
        "independent",
        "indicate",
        "individual",
        "industrial",
        "industry",
        "influence",
        "information",
        "inside",
        "instance",
        "instant",
        "instead",
        "instrument",
        "interest",
        "interior",
        "into",
        "into",
        "introduced",
        "invented",
        "involved",
        "iron",
        "is",
        "island",
        "it",
        "it",
        "its",
        "its",
        "itself",
        "jack",
        "jar",
        "jet",
        "job",
        "join",
        "joined",
        "journey",
        "joy",
        "judge",
        "jump",
        "jungle",
        "just",
        "just",
        "keep",
        "kept",
        "key",
        "kids",
        "kill",
        "kind",
        "kitchen",
        "knew",
        "knife",
        "know",
        "know",
        "knowledge",
        "known",
        "label",
        "labor",
        "lack",
        "lady",
        "laid",
        "lake",
        "lamp",
        "land",
        "language",
        "large",
        "larger",
        "largest",
        "last",
        "late",
        "later",
        "laugh",
        "law",
        "lay",
        "layers",
        "lead",
        "leader",
        "leaf",
        "learn",
        "least",
        "leather",
        "leave",
        "leaving",
        "led",
        "left",
        "leg",
        "length",
        "lesson",
        "let",
        "letter",
        "level",
        "library",
        "lie",
        "life",
        "lift",
        "light",
        "like",
        "like",
        "likely",
        "limited",
        "line",
        "lion",
        "lips",
        "liquid",
        "list",
        "listen",
        "little",
        "live",
        "living",
        "load",
        "local",
        "locate",
        "location",
        "log",
        "lonely",
        "long",
        "longer",
        "look",
        "look",
        "loose",
        "lose",
        "loss",
        "lost",
        "lot",
        "loud",
        "love",
        "lovely",
        "low",
        "lower",
        "luck",
        "lucky",
        "lunch",
        "lungs",
        "lying",
        "machine",
        "machinery",
        "mad",
        "made",
        "magic",
        "magnet",
        "mail",
        "main",
        "mainly",
        "major",
        "make",
        "make",
        "making",
        "man",
        "managed",
        "manner",
        "manufacturing",
        "many",
        "map",
        "mark",
        "market",
        "married",
        "mass",
        "massage",
        "master",
        "material",
        "mathematics",
        "matter",
        "may",
        "maybe",
        "me",
        "me",
        "meal",
        "mean",
        "means",
        "meant",
        "measure",
        "meat",
        "medicine",
        "meet",
        "melted",
        "member",
        "memory",
        "men",
        "mental",
        "merely",
        "met",
        "metal",
        "method",
        "mice",
        "middle",
        "might",
        "mighty",
        "mile",
        "military",
        "milk",
        "mill",
        "mind",
        "mine",
        "minerals",
        "minute",
        "mirror",
        "missing",
        "mission",
        "mistake",
        "mix",
        "mixture",
        "model",
        "modern",
        "molecular",
        "moment",
        "money",
        "monkey",
        "month",
        "mood",
        "moon",
        "more",
        "morning",
        "most",
        "most",
        "mostly",
        "mother",
        "motion",
        "motor",
        "mountain",
        "mouse",
        "mouth",
        "move",
        "movement",
        "movie",
        "moving",
        "mud",
        "muscle",
        "music",
        "musical",
        "must",
        "my",
        "my",
        "myself",
        "mysterious",
        "nails",
        "name",
        "nation",
        "national",
        "native",
        "natural",
        "naturally",
        "nature",
        "near",
        "nearby",
        "nearer",
        "nearest",
        "nearly",
        "necessary",
        "neck",
        "needed",
        "needle",
        "needs",
        "negative",
        "neighbor",
        "neighborhood",
        "nervous",
        "nest",
        "never",
        "new",
        "new",
        "news",
        "newspaper",
        "next",
        "nice",
        "night",
        "nine",
        "no",
        "no",
        "nobody",
        "nodded",
        "noise",
        "none",
        "noon",
        "nor",
        "north",
        "nose",
        "not",
        "not",
        "note",
        "noted",
        "nothing",
        "notice",
        "noun",
        "now",
        "now",
        "number",
        "numeral",
        "nuts",
        "object",
        "observe",
        "obtain",
        "occasionally",
        "occur",
        "ocean",
        "of",
        "of",
        "off",
        "offer",
        "office",
        "officer",
        "official",
        "oil",
        "old",
        "older",
        "oldest",
        "on",
        "on",
        "once",
        "one",
        "one",
        "only",
        "only",
        "onto",
        "open",
        "operation",
        "opinion",
        "opportunity",
        "opposite",
        "or",
        "or",
        "orange",
        "orbit",
        "order",
        "ordinary",
        "organization",
        "organized",
        "origin",
        "original",
        "other",
        "other",
        "ought",
        "our",
        "our",
        "ourselves",
        "out",
        "out",
        "outer",
        "outline",
        "outside",
        "over",
        "over",
        "own",
        "owner",
        "oxygen",
        "pack",
        "package",
        "page",
        "paid",
        "pain",
        "paint",
        "pair",
        "palace",
        "pale",
        "pan",
        "paper",
        "paragraph",
        "parallel",
        "parent",
        "park",
        "part",
        "particles",
        "particular",
        "particularly",
        "partly",
        "parts",
        "party",
        "pass",
        "passage",
        "past",
        "path",
        "pattern",
        "pay",
        "peace",
        "pen",
        "pencil",
        "people",
        "people",
        "per",
        "percent",
        "perfect",
        "perfectly",
        "perhaps",
        "period",
        "person",
        "personal",
        "pet",
        "phrase",
        "physical",
        "piano",
        "pick",
        "picture",
        "pictured",
        "pie",
        "piece",
        "pig",
        "pile",
        "pilot",
        "pine",
        "pink",
        "pipe",
        "pitch",
        "place",
        "plain",
        "plan",
        "plane",
        "planet",
        "planned",
        "planning",
        "plant",
        "plastic",
        "plate",
        "plates",
        "play",
        "pleasant",
        "please",
        "pleasure",
        "plenty",
        "plural",
        "plus",
        "pocket",
        "poem",
        "poet",
        "poetry",
        "point",
        "pole",
        "police",
        "policeman",
        "political",
        "pond",
        "pony",
        "pool",
        "poor",
        "popular",
        "population",
        "porch",
        "port",
        "position",
        "positive",
        "possible",
        "possibly",
        "post",
        "pot",
        "potatoes",
        "pound",
        "pour",
        "powder",
        "power",
        "powerful",
        "practical",
        "practice",
        "prepare",
        "present",
        "president",
        "press",
        "pressure",
        "pretty",
        "prevent",
        "previous",
        "price",
        "pride",
        "primitive",
        "principal",
        "principle",
        "printed",
        "private",
        "prize",
        "probably",
        "problem",
        "process",
        "produce",
        "product",
        "production",
        "program",
        "progress",
        "promised",
        "proper",
        "properly",
        "property",
        "protection",
        "proud",
        "prove",
        "provide",
        "public",
        "pull",
        "pupil",
        "pure",
        "purple",
        "purpose",
        "push",
        "put",
        "putting",
        "quarter",
        "queen",
        "question",
        "quick",
        "quickly",
        "quiet",
        "quietly",
        "quite",
        "rabbit",
        "race",
        "radio",
        "railroad",
        "rain",
        "raise",
        "ran",
        "ranch",
        "range",
        "rapidly",
        "rate",
        "rather",
        "raw",
        "rays",
        "reach",
        "read",
        "reader",
        "ready",
        "real",
        "realize",
        "rear",
        "reason",
        "recall",
        "receive",
        "recent",
        "recently",
        "recognize",
        "record",
        "red",
        "refer",
        "refused",
        "region",
        "regular",
        "related",
        "relationship",
        "religious",
        "remain",
        "remarkable",
        "remember",
        "remove",
        "repeat",
        "replace",
        "replied",
        "report",
        "represent",
        "require",
        "research",
        "respect",
        "rest",
        "result",
        "return",
        "review",
        "rhyme",
        "rhythm",
        "rice",
        "rich",
        "ride",
        "riding",
        "right",
        "ring",
        "rise",
        "rising",
        "river",
        "road",
        "roar",
        "rock",
        "rocket",
        "rocky",
        "rod",
        "roll",
        "roof",
        "room",
        "root",
        "rope",
        "rose",
        "rough",
        "round",
        "route",
        "row",
        "rubbed",
        "rubber",
        "rule",
        "ruler",
        "run",
        "running",
        "rush",
        "sad",
        "saddle",
        "safe",
        "safety",
        "said",
        "sail",
        "sale",
        "salmon",
        "salt",
        "same",
        "sand",
        "sang",
        "sat",
        "satellites",
        "satisfied",
        "save",
        "saved",
        "saw",
        "say",
        "say",
        "scale",
        "scared",
        "scene",
        "school",
        "science",
        "scientific",
        "scientist",
        "score",
        "screen",
        "sea",
        "search",
        "season",
        "seat",
        "second",
        "secret",
        "section",
        "see",
        "see",
        "seed",
        "seeing",
        "seems",
        "seen",
        "seldom",
        "select",
        "selection",
        "sell",
        "send",
        "sense",
        "sent",
        "sentence",
        "separate",
        "series",
        "serious",
        "serve",
        "service",
        "sets",
        "setting",
        "settle",
        "settlers",
        "seven",
        "several",
        "shade",
        "shadow",
        "shake",
        "shaking",
        "shall",
        "shallow",
        "shape",
        "share",
        "sharp",
        "she",
        "she",
        "sheep",
        "sheet",
        "shelf",
        "shells",
        "shelter",
        "shine",
        "shinning",
        "ship",
        "shirt",
        "shoe",
        "shoot",
        "shop",
        "shore",
        "short",
        "shorter",
        "shot",
        "should",
        "shoulder",
        "shout",
        "show",
        "shown",
        "shut",
        "sick",
        "sides",
        "sight",
        "sign",
        "signal",
        "silence",
        "silent",
        "silk",
        "silly",
        "silver",
        "similar",
        "simple",
        "simplest",
        "simply",
        "since",
        "sing",
        "single",
        "sink",
        "sister",
        "sit",
        "sitting",
        "situation",
        "six",
        "size",
        "skill",
        "skin",
        "sky",
        "slabs",
        "slave",
        "sleep",
        "slept",
        "slide",
        "slight",
        "slightly",
        "slip",
        "slipped",
        "slope",
        "slow",
        "slowly",
        "small",
        "smaller",
        "smallest",
        "smell",
        "smile",
        "smoke",
        "smooth",
        "snake",
        "snow",
        "so",
        "so",
        "soap",
        "social",
        "society",
        "soft",
        "softly",
        "soil",
        "solar",
        "sold",
        "soldier",
        "solid",
        "solution",
        "solve",
        "some",
        "some",
        "somebody",
        "somehow",
        "someone",
        "something",
        "sometime",
        "somewhere",
        "son",
        "song",
        "soon",
        "sort",
        "sound",
        "source",
        "south",
        "southern",
        "space",
        "speak",
        "special",
        "species",
        "specific",
        "speech",
        "speed",
        "spell",
        "spend",
        "spent",
        "spider",
        "spin",
        "spirit",
        "spite",
        "split",
        "spoken",
        "sport",
        "spread",
        "spring",
        "square",
        "stage",
        "stairs",
        "stand",
        "standard",
        "star",
        "stared",
        "start",
        "state",
        "statement",
        "station",
        "stay",
        "steady",
        "steam",
        "steel",
        "steep",
        "stems",
        "step",
        "stepped",
        "stick",
        "stiff",
        "still",
        "stock",
        "stomach",
        "stone",
        "stood",
        "stop",
        "stopped",
        "store",
        "storm",
        "story",
        "stove",
        "straight",
        "strange",
        "stranger",
        "straw",
        "stream",
        "street",
        "strength",
        "stretch",
        "strike",
        "string",
        "strip",
        "strong",
        "stronger",
        "struck",
        "structure",
        "struggle",
        "stuck",
        "student",
        "studied",
        "studying",
        "subject",
        "substance",
        "success",
        "successful",
        "such",
        "sudden",
        "suddenly",
        "sugar",
        "suggest",
        "suit",
        "sum",
        "summer",
        "sun",
        "sunlight",
        "supper",
        "supply",
        "support",
        "suppose",
        "sure",
        "surface",
        "surprise",
        "surrounded",
        "swam",
        "sweet",
        "swept",
        "swim",
        "swimming",
        "swing",
        "swung",
        "syllable",
        "symbol",
        "system",
        "table",
        "tail",
        "take",
        "take",
        "taken",
        "tales",
        "talk",
        "tall",
        "tank",
        "tape",
        "task",
        "taste",
        "taught",
        "tax",
        "tea",
        "teach",
        "teacher",
        "team",
        "tears",
        "teeth",
        "telephone",
        "television",
        "tell",
        "temperature",
        "ten",
        "tent",
        "term",
        "terrible",
        "test",
        "than",
        "than",
        "thank",
        "that",
        "that",
        "the",
        "thee",
        "their",
        "them",
        "them",
        "themselves",
        "then",
        "then",
        "theory",
        "there",
        "there",
        "therefore",
        "these",
        "these",
        "they",
        "they",
        "thick",
        "thin",
        "thing",
        "think",
        "think",
        "third",
        "thirty",
        "this",
        "this",
        "those",
        "thou",
        "though",
        "thought",
        "thousand",
        "thread",
        "three",
        "threw",
        "throat",
        "through",
        "throughout",
        "throw",
        "thrown",
        "thumb",
        "thus",
        "thy",
        "tide",
        "tie",
        "tight",
        "tightly",
        "till",
        "time",
        "time",
        "tin",
        "tiny",
        "tip",
        "tired",
        "title",
        "to",
        "to",
        "tobacco",
        "today",
        "together",
        "told",
        "tomorrow",
        "tone",
        "tongue",
        "tonight",
        "too",
        "took",
        "tool",
        "top",
        "topic",
        "torn",
        "total",
        "touch",
        "toward",
        "tower",
        "town",
        "toy",
        "trace",
        "track",
        "trade",
        "traffic",
        "trail",
        "train",
        "transportation",
        "trap",
        "travel",
        "treated",
        "tree",
        "triangle",
        "tribe",
        "trick",
        "tried",
        "trip",
        "troops",
        "tropical",
        "trouble",
        "truck",
        "trunk",
        "truth",
        "try",
        "tube",
        "tune",
        "turn",
        "twelve",
        "twenty",
        "twice",
        "two",
        "two",
        "type",
        "typical",
        "uncle",
        "under",
        "underline",
        "understanding",
        "unhappy",
        "union",
        "unit",
        "universe",
        "unknown",
        "unless",
        "until",
        "unusual",
        "up",
        "up",
        "upon",
        "upper",
        "upward",
        "us",
        "us",
        "use",
        "use",
        "useful",
        "using",
        "usual",
        "usually",
        "valley",
        "valuable",
        "value",
        "vapor",
        "variety",
        "various",
        "vast",
        "vegetable",
        "verb",
        "vertical",
        "very",
        "vessels",
        "victory",
        "view",
        "village",
        "visit",
        "visitor",
        "voice",
        "volume",
        "vote",
        "vowel",
        "voyage",
        "wagon",
        "wait",
        "walk",
        "wall",
        "want",
        "want",
        "war",
        "warm",
        "warn",
        "was",
        "wash",
        "waste",
        "watch",
        "water",
        "wave",
        "way",
        "way",
        "we",
        "we",
        "weak",
        "wealth",
        "wear",
        "weather",
        "week",
        "weigh",
        "weight",
        "welcome",
        "well",
        "well",
        "went",
        "were",
        "west",
        "western",
        "wet",
        "whale",
        "what",
        "what",
        "whatever",
        "wheat",
        "wheel",
        "when",
        "when",
        "whenever",
        "where",
        "wherever",
        "whether",
        "which",
        "which",
        "while",
        "whispered",
        "whistle",
        "white",
        "who",
        "who",
        "whole",
        "whom",
        "whose",
        "why",
        "wide",
        "widely",
        "wife",
        "wild",
        "will",
        "will",
        "willing",
        "win",
        "wind",
        "window",
        "wing",
        "winter",
        "wire",
        "wise",
        "wish",
        "with",
        "with",
        "within",
        "without",
        "wolf",
        "women",
        "won",
        "wonder",
        "wonderful",
        "wood",
        "wooden",
        "wool",
        "word",
        "wore",
        "work",
        "worker",
        "world",
        "worried",
        "worry",
        "worse",
        "worth",
        "would",
        "wrapped",
        "write",
        "writer",
        "writing",
        "written",
        "wrong",
        "wrote",
        "yard",
        "year",
        "yellow",
        "yes",
        "yesterday",
        "yet",
        "you",
        "young",
        "younger",
        "your",
        "yourself",
        "youth",
        "zebra",
        "zero",
        "zipper",
        "zoo",
        "zulu",
      ];

      const randomIndex = Math.floor(Math.random() * commonWords.length);
      let selectedWord = commonWords[randomIndex];

      if (selectedWord.length <= 3) {
        const randomIndex2 = Math.floor(Math.random() * commonWords.length);
        const additionalWord = commonWords[randomIndex2];
        selectedWord += ` ${additionalWord}`;
      }

      return selectedWord;
    };

    const movieBtnAction = (action, mId, movieTitle) => {
      return (
        (dialogTitle.value = movieTitle),
        (movieId.value = mId),
        watchMovies.value.find((movie) => movie.movieID === mId) ? (movieWatchDate.value = watchMovies.value.find((movie) => movie.movieID === mId).watchDate) : (movieWatchDate.value = ""),
        (dialogAction.value = action),
        action !== "Delete" && (openAgendaDialog.value = true)
      );
    };

    const showHiddenBtns = (mId, btnLabel) => {
      const hasMovieAgenda = watchMovies.value.filter((mvid) => mvid.movieID === mId)[0];
      const label = btnLabel;

      if ((!hasMovieAgenda && label == "Delete") || (hasMovieAgenda && label == "Add") || (!hasMovieAgenda && label == "Edit")) {
        return "hidden";
      }
    };

    const fetchMovie = () => {
      // Asynchronous FN to fetch API
      async function ftMovie() {
        let resp = await fetch(flashURL.value, {
          method: "get",
          redirect: "follow",
        });

        if (!resp.ok) {
          throw new Error(`HTTP error! status: ${resp.error}`);
        }

        return resp.json();
      }

      // Calls the FN to populate the movie list
      ftMovie()
        .then((resp) => {
          if (resp.Response == "False") {
            throw new Error(resp.Error);
          }

          moviesTitles.value = resp.Search;
          return fetchMovieDetails();
        })
        .catch((e) => {
          return (progressLoader.value = false), (noMovie.value = true), console.error(e);
        });
    };

    const fetchMovieDetails = () => {
      moviesDetails.value = [];
      let detailsTerms = new Array();
      let detailsUrls = new Array();
      const fetchDetails = new Array();

      moviesTitles.value.forEach((movie) => {
        detailsTerms.push(movie.Title);
      });

      detailsTerms.forEach((term) => {
        const detailUrl = `https://www.omdbapi.com/?t=${term}&type=movie&apikey=${api_key}`;

        detailsUrls.push(detailUrl);
      });

      detailsUrls.forEach((detailUrl) => {
        const detailPromise = fetch(detailUrl).then((resp) => {
          if (resp.Response == "False") {
            throw new Error(resp.Error);
          }

          return resp.json();
        });

        fetchDetails.push(detailPromise);
      });

      Promise.all(fetchDetails)
        .then((detailArray) => {
          progressLoader.value = false;

          detailArray.forEach((data) => {
            return moviesDetails.value.push(data);
          });

          return sortAndFilter();
        })
        .catch((err) => {
          console.error(err);
        });
    };

    const sortAndFilter = () => {
      const uniqueMovies = moviesDetails.value
        .sort((a, b) => b.Year - a.Year)
        .filter((movie, index, self) => {
          const titles = self.map((movie) => movie.Title);
          return titles.indexOf(movie.Title) === index;
        });

      return (moviesDetails.value = uniqueMovies);
    };

    const search = () => {
      // Setting defaults
      moviesTitles.value = [];
      moviesDetails.value = [];
      noMovie.value = false;
      progressLoader.value = true;

      // Breaks if search field wrong
      if ((!searchTerm.value && !luckyMethod.value) || (searchTerm.value.length < 3 && !luckyMethod.value)) {
        return false;
      }

      luckyMethod.value && (searchTerm.value = getRandomWord());

      flashURL.value = new URL(`https://www.omdbapi.com/?s=${searchTerm.value}&type=movie&apikey=${api_key}`);
      fetchMovie();
    };

    const getStreamingList = () => {
      movieAddedLoading.value = true;

      api_streaming
        .get("/get", {
          headers: {
            "X-RapidAPI-Key": streaming_key,
          },
          params: {
            imdb_id: movieId.value,
            output_language: "en",
          },
        })
        .then((res) => {
          const countryCode = selectedCountry.value;
          const rawData = res.data.result.streamingInfo[countryCode];

          const uniqueData = new Set();

          // Filtering and creating an array with unique service entries
          const uniqueServices = rawData.filter((item) => {
            // Check if the service is not in the Set
            if (!uniqueData.has(item.service)) {
              // Add the service to the Set
              uniqueData.add(item.service);
              return true;
            }
            return false; // Exclude duplicates from the filtered array
          });

          return (streamingList.value = uniqueServices);
        })
        .catch((e) => {
          console.error(e);
        })
        .finally(() => {
          const editMovie = watchMovies.value.find((movie) => movie.movieID == movieId.value);

          if (editMovie === undefined) addMovieAgenda();
          else {
            watchMovies.value.find((movie) => movie.movieID == movieId.value).streamingList = streamingList.value;

            return $q.value.notify({
              type: "info",
              message: "Movie editted successful. Nice!",
            });
          }

          return (movieAddedLoading.value = false);
        });
    };

    const getCountries = () => {
      const ctList = localStorage.moviesContriesList ? JSON.parse(localStorage.moviesContriesList) : null;

      if (ctList) {
        ctList.forEach((e) => {
          const country = {
            countryCode: e.countryCode,
            name: e.name,
          };

          return countriesList.value.push(country);
        });
      } else {
        api_streaming
          .get("/countries", {
            headers: {
              "X-RapidAPI-Key": streaming_key,
            },
          })
          .then((res) => {
            return (countriesList.value = Object.values(res.data.result));
          });
      }
    };

    const checkMovie = () => {
      selectedCountry.value = "";

      countrySearch.value.length === 0 && (countrySearch.value = "United States");

      // Capitalize the country name for the API
      const capitalizeString = (str) =>
        str
          .split(" ")
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
          .join(" ");

      countrySearch.value = capitalizeString(countrySearch.value);

      // Search in the API by the string received
      let country = countriesList.value.filter((country) => country.name === countrySearch.value);

      if (country.length > 0) {
        selectedCountry.value = country[0].countryCode;

        return $q.value.notify({
          type: "positive",
          message: `Okay. We'll search by streaming services from ${country[0].name.toUpperCase()}`,
        });
      } else {
        return $q.value.notify({
          type: "negative",
          message: "Country not found. Please check it",
        });
      }
    };

    const addMovieAgenda = () => {
      // Adds the movie into an Array and closes the calendar dialog
      const newMovieagenda = {
        watchDate: !movieWatchDate.value == "" ? movieWatchDate.value : today(),
        movieID: movieId.value,
        movieTitle: dialogTitle.value,
        streamingList: streamingList.value,
        streamingCountry: selectedCountry.value,
        streamingCountryName: countrySearch.value,
        watched: false,
      };

      watchMovies.value.push(newMovieagenda);

      openAgendaDialog.value = false;

      return $q.value.notify({
        type: "positive",
        message: "Movie added successful. Good fun!",
      });
    };

    const editMovieAgenda = () => {
      watchMovies.value.find((movie) => movie.movieID == movieId.value).watchDate = movieWatchDate.value;
      watchMovies.value.find((movie) => movie.movieID == movieId.value).streamingCountry = selectedCountry.value;
      watchMovies.value.find((movie) => movie.movieID == movieId.value).streamingCountryName = countrySearch.value;
      openAgendaDialog.value = false;

      return getStreamingList();
    };

    const delMovieAgenda = (mId) => {
      const movieToDelete = watchMovies.value.filter((movie) => movie.movieID !== mId);

      watchMovies.value = movieToDelete;

      return $q.value.notify({
        type: "info",
        message: "Movie removed successful.",
      });
    };

    getCountries(); // Gets countrie list from API on created

    onMounted(() => {
      movieWatchDate.value = today();

      if (localStorage.watchMovies && localStorage.watchMovies !== "undefined") {
        return (watchMovies.value = JSON.parse(localStorage.watchMovies));
      }
    });

    return {
      agendaButtons,
      countriesList,
      countrySearch,
      dialogAction,
      dialogTitle,
      flashURL,
      luckyMethod,
      movieAddedLoading,
      movieId,
      movieWatchDate,
      moviesDetails,
      moviesTitles,
      openAgendaDialog,
      progressLoader,
      searchRules,
      searchTerm,
      selectedCountry,
      streamingList,
      noMovie,
      watchMovies,
      checkMovie,
      getStreamingList,
      editMovieAgenda,
      delMovieAgenda,
      movieBtnAction,
      movieWatchDateOpt,
      search,
      showHiddenBtns,
    };
  },
  watch: {
    watchMovies: {
      // Watches the add movie action and appends the local storage with it
      handler(addMovieAgenda) {
        localStorage.watchMovies = JSON.stringify(addMovieAgenda);
      },
      deep: true,
    },
    countriesList: {
      handler(getCountries) {
        localStorage.moviesContriesList = JSON.stringify(getCountries);
      },
      deep: true,
    },
  },
};
</script>

<style lang="scss" scoped>
.right-\[20px\] {
  right: 20px;
}
.right-\[90px\] {
  right: 90px;
}

:deep(.q-date__header) {
  .q-date__header-subtitle {
    display: none;
  }
}
</style>
